language: node_js
sudo: required
dist: trusty
before_install:
  - export DISPLAY=:99.0
  - export CXX=g++-4.8
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
before_script:
  - jdk_switcher use oraclejdk8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
jobs:
  include:
    - name: "Lint"
      env: TEST_SUITE=standard
    - name: "Functional tests (Puppeteer)"
      env: TEST_SUITE=karma
    - name: "Integration tests (SauceLabs)"
      env: TEST_SUITE=wdio
      if: type = pull_request OR branch = master
script:
  - npm run $TEST_SUITE
after_success:
  - cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
